from common import *
from h1_flows import mk, L1
FAULT = "window.__fail = new Set(); const _p = IDBObjectStore.prototype.put; IDBObjectStore.prototype.put = function(...a){ if (window.__fail.has(this.name)) throw new DOMException('quota','QuotaExceededError'); return _p.apply(this, a) }"
def state(pg): return pg.inner_text('#app')[:70].replace('\n', ' | ')
with sync_playwright() as p:
    b = p.chromium.launch()
    # 1. ordinary lesson (unit 0 rules): fail progress write on finish, then Try again
    ctx, pg = newpage(b, init=FAULT); quick_profile(pg, 'F')
    click(pg, "button:has-text('Start:')"); pg.wait_for_timeout(900)
    for _ in range(2): pg.evaluate("()=>document.querySelector('.lesson .btn-primary')?.click()"); pg.wait_for_timeout(500)
    pg.evaluate("window.__fail.add('progress')")
    pg.evaluate("()=>document.querySelector('.lesson .btn-primary')?.click()"); pg.wait_for_timeout(1500)
    print('1 after failed finish:', state(pg), '| celebrate', bool(pg.query_selector('.celebrate')))
    pg.evaluate("window.__fail.clear()")
    burst_sel(pg, "button:has-text('Try again')", (0, 100, 200)); pg.wait_for_timeout(2000)
    c, d = counts(pg); print('1 after retry x3:', state(pg), '| celebrations', pg.evaluate("document.querySelectorAll('.celebrate').length"), 'lessons', [list(v.get('lessons', {})) for x in d['progress'] for v in x['units'].values()])
    ctx.close()
    # 2. quiz: markUnit fails
    ctx, pg = newpage(b, init=FAULT); quick_profile(pg, 'Q'); mk(pg, L1 + ['marks', 'join', 'blend', 'W1', 'W2', 'W3', 'W4', 'read'])
    click(pg, "button:has-text('Continue:'), button:has-text('Start:')"); pg.wait_for_timeout(1000)
    pg.evaluate("""()=>{const lis=[...document.querySelectorAll('.lesson ol > li')]; lis.forEach(li=>{const rom=li.querySelector('b').innerText; [...li.querySelectorAll('.tile')].find(t=>t.getAttribute('aria-label')===rom).click()})}""")
    pg.evaluate("window.__fail.add('progress')")
    pg.evaluate("()=>document.querySelector('.lesson button.act').click()"); pg.wait_for_timeout(2000)
    btns = pg.evaluate("[...document.querySelectorAll('.lesson button:not(.tile)')].map(b=>b.innerText.trim()).filter(Boolean)")
    print('2 quiz with failing progress write: buttons', btns, '| text tail:', pg.inner_text('.lesson')[-120:].replace('\n', ' | '), '| toast', toast(pg), pg._errs[:2])
    ctx.close()
    # 3. quiz passes markUnit but ensureCards fails (cards store)
    ctx, pg = newpage(b, init=FAULT); quick_profile(pg, 'Q3'); mk(pg, L1 + ['marks', 'join', 'blend', 'W1', 'W2', 'W3', 'W4', 'read'])
    click(pg, "button:has-text('Continue:'), button:has-text('Start:')"); pg.wait_for_timeout(1000)
    pg.evaluate("""()=>{const lis=[...document.querySelectorAll('.lesson ol > li')]; lis.forEach(li=>{const rom=li.querySelector('b').innerText; [...li.querySelectorAll('.tile')].find(t=>t.getAttribute('aria-label')===rom).click()})}""")
    pg.evaluate("window.__fail.add('cards')")
    pg.evaluate("()=>document.querySelector('.lesson button.act').click()"); pg.wait_for_timeout(2500)
    btns = pg.evaluate("[...document.querySelectorAll('.lesson button:not(.tile)')].map(b=>b.innerText.trim()).filter(Boolean)")
    c, d = counts(pg)
    print('3 quiz with failing cards write: buttons', btns, 'passed', [(u, v.get('passed')) for x in d['progress'] for u, v in x['units'].items()], 'cards', c['cards'], '| toast', toast(pg))
    pg.evaluate("window.__fail.clear()"); pg.reload(); pg.wait_for_timeout(2500)
    c, d = counts(pg); print('3 after reload: cards', c['cards'], 'today:', state(pg))
    ctx.close()
    b.close()
