from common import *
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx, pg = newpage(b); pg.goto(BASE + '?skiponb'); pg.wait_for_timeout(1500)
    click(pg, 'text=Just me'); pg.wait_for_timeout(400); click(pg, 'text=+ Add a learner'); pg.wait_for_timeout(400)
    pg.fill('input[placeholder=Name]', '  <b>' + 'x' * 300 + '</b>  '); click(pg, "button:has-text('Start')"); pg.wait_for_timeout(1500)
    c, d = counts(pg); print('addProfile name:', repr(d['profiles'][0]['name']), len(d['profiles'][0]['name']))
    ctx.close()
    ctx, pg = newpage(b); pg.goto(BASE); pg.wait_for_timeout(2200)
    for s_, w in [("text=Let's begin", 500), ('.ob-sleeper', 2800)]: click(pg, s_); pg.wait_for_timeout(w)
    click(pg, '.ob-sw >> nth=0'); pg.wait_for_timeout(300); click(pg, '.ob-cta'); pg.wait_for_timeout(500); click(pg, ".ob-opt:has-text('My child')"); pg.wait_for_timeout(1600)
    print('ob-name maxlength attr:', pg.evaluate("document.querySelector('#ob-name').maxLength"))
    pg.fill('#ob-name', '<i>' + 'y' * 300); pg.wait_for_timeout(300); click(pg, '.ob-cta'); pg.wait_for_timeout(800)
    print('onb saved name:', repr(pg.evaluate("__dump().then(d=>(d.settings.find(s=>s.key==='onb')||{}).value?.a?.name)")))
    print('screen:', pg.inner_text('.ob')[:120].replace('\n', ' | '), sw(pg))
    ctx.close()
    # teacher add child + edit prompt with long name
    ctx, pg = newpage(b); pg.goto(BASE + '?skiponb'); pg.wait_for_timeout(1200)
    pg.evaluate("async()=>{await __put('settings',{key:'mode',value:'school'}); await __put('settings',{key:'teacherPin',value:'1234'}); await __put('profiles',{id:'t1',kind:'learner',name:'Bil',track:'child',grade:2,createdAt:1})}"); pg.reload(); pg.wait_for_timeout(1500)
    pg.evaluate("[...document.querySelectorAll('button')].find(b=>/Teacher/.test(b.innerText))?.click()"); pg.wait_for_timeout(400)
    pg.fill('input[type=password]', '1234'); pg.evaluate("[...document.querySelectorAll('button')].find(b=>/Unlock/.test(b.innerText)).click()"); pg.wait_for_timeout(1200)
    pg.fill('input[placeholder=Name]', '<u>' + 'z' * 300); pg.evaluate("[...document.querySelectorAll('button')].find(b=>b.innerText==='Add child').click()"); pg.wait_for_timeout(1000)
    ps = counts(pg)[1]['profiles']; print('teacher add child names:', [(len(x['name']), x['name'][:12]) for x in ps])
    ctx.close(); b.close()
