// Learner mode: Today, Session, Lesson, Review, Read, Test yourself, Progress, Settings.
import { db, uid } from './db.js';
import { C, play, W, shuffle, wordKey, sentKey, el, toast, bandFor, recBand } from './content.js';
import * as D from './drills.js';
import * as S from './session.js';
import { renderDashboard } from './dashboard.js';
import { renderPath, runLesson, lessonState, countUp, dailyGoal, goalFlag, unlockInfo, retrigger, sGet, sSet } from './path.js';
import { setMarko } from './marko.js';
import { icon, mascot, confetti, unitArt, LESSON_ICON, avatar } from './icons.js';
import { fx, burst } from './fx.js';
import { askGrownup } from './gate.js';
import { openPractice } from './practice.js';
import { esc, tapLock } from './safe.js';
import { restoreFromFile } from './restore.js';

export async function renderLearner(root, ctx) {
  const { profile } = ctx; const st = { tab: 'today' };
  const marks = () => ctx.settings.marks !== false && (st.unitN ?? 0) <= 10;
  const styleName = () => ctx.settings.style || 'naskh';
  const dctx = { record: (drill, item, ok, ms) => st.preview ? undefined : S.recordAttempt(profile.id, st.unitN ?? 0, drill, item, ok, ms) };
  try { await S.ensureCards(profile.id, await S.currentUnit(profile.id)); } catch (e) { if (ctx.recover) return ctx.recover(e); throw e; }
  root.innerHTML = ''; const main = el('div'); root.append(main);
  const nav = el('div', 'bottom'); root.append(nav);
  // Tabs: children get 4 (Learn, Review, Read, Me; Units sits behind "All units" on Learn), everyone else keeps 6.
  // Each tab has its own palette colour (--tc icon/pill, --td label on the light pill); the filled icon pops once when picked.
  const kid = () => profile.track === 'child';
  const TAB = { today: ['home', 'Learn', '#1E9C8F', '#126B62'], units: ['units', 'Units', '#F2A93B', '#94590C'], review: ['review', 'Review', 'var(--coral)', '#B03F22'], read: ['read', 'Read', '#4F5FD0', '#2E3A8C'], me: ['me', 'Me', '#5FA55A', '#2F6A2C'], progress: ['progress', 'Progress', '#5FA55A', '#2F6A2C'], more: ['more', 'More', '#D97AA6', '#9C3A6A'] };
  const tabKeys = () => kid() ? ['today', 'review', 'read', 'me'] : ['today', 'units', 'review', 'read', 'progress', 'more'];
  const navOf = t => kid() ? ({ units: 'today', lesson: 'today', progress: 'me', more: 'me', test: 'me' }[t] || t) : ({ me: 'progress', lesson: 'units', test: 'more' }[t] || t);
  function buildNav() { nav.innerHTML = ''; nav.dataset.n = tabKeys().length; tabKeys().forEach(k => { const [ic, lab, c, d] = TAB[k]; const b = el('button', '', `${icon(ic + '_f')}<span class="lb">${lab}</span>`); b.style.setProperty('--tc', c); b.style.setProperty('--td', d); b.onclick = () => { st.tab = k; render(); }; b.dataset.k = k; nav.append(b); }); }
  let navKid = kid(); buildNav();
  // renders never interleave: a double tap on a tab queues a second render after the first, instead of both appending to the same screen
  let chain = Promise.resolve(); const render = () => (chain = chain.then(doRender, doRender));
  async function doRender() { st.preview = false; if (navKid !== kid()) { navKid = kid(); buildNav(); } if (st.tab === 'me' && !kid()) st.tab = 'progress'; const on = navOf(st.tab); [...nav.children].forEach(b => b.classList.toggle('active', b.dataset.k === on)); main.innerHTML = ''; main.className = 't-kids'; window.scrollTo(0, 0); try { await ({ today, units, review, read, progress, more, me, lesson, session, test, path }[st.tab])(); } catch (e) { if (ctx.recover) ctx.recover(e); else toast('This screen could not load. Please try again.'); } }
  const pctx = () => ({ profile, marks, styleName, dctx, unit0, aspirates, izafat, punctuation, unit11, sightDrill, go: t => { st.tab = t === 'path' ? 'today' : t; render(); }, openLesson: (u, i) => { st.unitN = u.n; st.tab = 'today'; main.innerHTML = ''; window.scrollTo(0, 0); runLesson(main, pctx(), u, i); } });
  async function path() { st.tab = 'today'; render(); }

  async function header(title, sub) { const h = el('div', 'row page-head', ''); h.style.justifyContent = 'space-between'; h.innerHTML = `<div><h1>${/^Good (morning|afternoon)/.test(title) ? '<span class="fx-sun"></span>' : ''}${title}</h1>${sub ? `<div class="muted">${sub}</div>` : ''}</div>`; const sun = h.querySelector('.fx-sun'); if (sun) sun.append(fx('sun_rays', { size: 34, loop: true })); const who = el('button', 'btn', `${icon('user')} ${esc(profile.name)}`); who.onclick = ctx.switchProfile; h.append(who); main.append(h); }

  async function today() {
    const cur = await S.currentUnit(profile.id); const s = await S.stats(profile.id);
    if (ctx.autoPlacement && cur === 0 && !s.sessions) { ctx.autoPlacement = false; return placement(); }
    const [pl, sk, goal] = await Promise.all([S.pearls(profile.id), S.streak(profile.id), dailyGoal(profile)]);
    // Above the fold: a painted courtyard with a big Marko in the middle, then ONE "today" card that holds the primary
    // button in its own zone (in the page flow, never floating over another card). The rest of the path is below the fold.
    const u = C.units[cur]; const ls = u ? await lessonState(profile.id, u) : null; const open = ls && !ls.passed && ls.current < ls.ls.length;
    const night = new Date().getHours() >= 18 || new Date().getHours() < 5;
    const hero = el('div', 'home-hero');
    hero.innerHTML = `<div class="hh-top"><div><h1>${greeting(profile)}</h1>${u ? `<div class="muted">Unit ${cur} · ${u.title}</div>` : ''}</div></div>
      <div class="hh-world" style="background-image:url(./img/scene_home_${night ? 'evening' : 'morning'}.webp)"><div class="hh-badges"><span class="hh-badge hh-pearl">${icon('star')} <b class="cu">${pl}</b><small>${pl === 1 ? 'pearl' : 'pearls'}</small></span><span class="hh-badge hh-goal" role="img" aria-label="Daily goal: ${Math.floor(goal.minutes)} of ${goal.goal} minutes"><span class="hh-ring"><svg viewBox="0 0 30 30" width="30" height="30"><circle class="rg-bg" cx="15" cy="15" r="12"/><circle class="rg-fg" cx="15" cy="15" r="12" pathLength="100"/></svg>${icon(goal.done ? 'check' : 'timer')}</span><b class="cu">${Math.floor(goal.minutes)}</b><small>/ ${goal.goal} min</small></span><span class="hh-badge hh-flame">${icon('flame')} ${sk ? `<b class="cu">${sk}</b><small>${sk === 1 ? 'day practised' : 'days practised'}</small>` : '<small>First day today</small>'}</span></div>
      <div class="hh-stage"><span class="hh-shadow"></span>${mascot(sk > 1 ? 'proud' : 'hello', 240, 'hh-marko')}<button class="hh-poke" aria-label="Tap Marko to say hi"></button><span class="hh-say">${open && ls.current > 0 ? `Ready for <b>${ls.ls[ls.current].title}</b>, ${esc(profile.name)}?` : pl ? `<span class="mem-line">Hi ${esc(profile.name)}! One lesson today?</span>` : `Hi ${esc(profile.name)}! Let's earn your first pearl.`}</span></div></div>`;
    const who = el('button', 'btn btn-chip hh-who', `${icon('user')} ${esc(profile.name)}`); who.setAttribute('aria-label', 'Switch learner'); who.onclick = ctx.switchProfile; hero.querySelector('.hh-top').append(who);
    if (open) {
      const n = Object.keys(ls.done).filter(id => ls.ls.some(l => l.id === id)).length, tot = ls.ls.length, l = ls.ls[ls.current];
      const card = el('div', 'card today-card', `<div class="tc-head"><span class="pill">Unit ${cur}</span><span class="tc-count">Lesson ${ls.current + 1} of ${tot}</span></div><div class="tc-main"><span class="tc-face">${l.icon && /[؀-ۿ]/.test(l.icon) ? `<span class="ur">${l.icon}</span>` : icon(LESSON_ICON[l.kind] || 'star')}</span><div><small class="muted">${n ? 'Up next' : 'Start here'}</small><b>${l.title}</b></div></div><div class="progress tc-bar"><i style="width:${Math.round(n / tot * 100)}%"></i></div>`);
      if (s.due) { const rv = el('button', 'btn btn-chip tc-review', `${icon('review')} ${s.due} to review`); rv.onclick = () => { st.tab = 'review'; render(); }; card.querySelector('.tc-head').append(rv); }
      const go = el('button', 'btn btn-primary btn-wide tc-go', `${n ? 'Continue' : 'Start'}: ${l.title}`); go.onclick = () => pctx().openLesson(u, ls.current); card.append(go); hero.append(card);
    } else if (s.due) { const card = el('div', 'card today-card'); const rv = el('button', 'btn btn-primary btn-wide tc-go', `${icon('review')} Review ${s.due} cards`); rv.onclick = () => { st.tab = 'review'; render(); }; card.append(rv); hero.append(card); }
    main.append(hero); alive(hero, goal, { pl, sk });
    // below the fold: the unit path (its own review card and docked button are dropped: the today card owns both)
    const pw = el('div', 'home-path'); await renderPath(pw, pctx()); pw.querySelectorAll(':scope > .card.row:not(.unit)').forEach(c => c.remove()); pw.querySelectorAll('.btn-primary').forEach(b => b.remove());
    if (unlockInfo.n != null && u) { const say = hero.querySelector('.hh-say'), mk = hero.querySelector('.hh-marko'); if (say) { say.dataset.keep = '1'; say.innerHTML = `Unit ${unlockInfo.n} is open, ${esc(profile.name)}!`; retrigger(say, 'say-pop', 0); } if (mk && mk._marko) setTimeout(() => setMarko(mk, 'cheer'), 500); }
    main.append(el('h3', 'hh-h3', 'Your path'), pw);
    if (kid()) { const all = el('button', 'card all-units', `<span class="au-ic">${icon('units_f')}</span><span><b>All units</b><small class="muted">See every unit and the letter library</small></span>${icon('next')}`); all.onclick = () => { st.tab = 'units'; render(); }; main.append(all); }
    if (s.wpm.length) { const last = s.wpm[s.wpm.length - 1]; main.append(el('div', 'card', `<b>Last reading speed:</b> ${last.wpm} words per minute <span class="pill ${bandFor(last.wpm)}">${bandFor(last.wpm)}</span>`)); }
    if (cur === 0 && !s.sessions) { const pl = el('div', 'card'); pl.innerHTML = '<h2>Already read some Urdu?</h2><p class="muted">A 2-minute placement check skips the units you already know.</p>'; const b = el('button', 'btn', 'Take the placement check'); b.onclick = () => placement(); pl.append(b); main.append(pl); }
    if (ctx.mode !== 'school') { const rp = el('button', 'btn btn-wide', 'Parent report for ' + profile.name); rp.onclick = () => parentReport(); main.append(rp); }
    if (cur === 0 && !s.sessions) main.append(el('details', 'card', `<summary style="font:600 16px var(--display);cursor:pointer">For parents: five things before letter one</summary><ol style="padding-left:18px"><li><b>Right to left.</b> The first letter is on the right.</li><li><b>Letters join</b> like cursive and change shape. Ten never join forward: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span></li><li><b>Dots decide the letter.</b> <span class="ur">ب پ ت ٹ ث ن ی</span> share one body.</li><li><b>Small marks are vowels.</b> We keep them until unit 11.</li><li><b>Two typefaces</b>, Naskh for learning and Nastaliq for print. Switch in More.</li></ol>`));
  }

  // round 9b: the Today scene comes alive: count-ups, goal ring, flame, tap-to-poke Marko, unprompted waves
  const POKE = (n) => [`Hi ${n}!`, 'Ready to read?', 'Alif is my friend', 'Hee hee, that tickles!', `You are doing great, ${n}`, 'Shall we find a letter?', 'Ba, ba, baa!', `I like reading with you, ${n}`];
  function alive(hero, goal, { pl, sk }) {
    const pid = profile.id, rm = matchMedia('(prefers-reduced-motion: reduce)').matches; const bs = hero.querySelectorAll('.hh-badge b.cu');
    const prevSk = sGet(`urc-today-${pid}-streak`); const ignite = prevSk != null && sk > prevSk;
    countUp(bs[0], pl, { key: `urc-today-${pid}-pearls` }); countUp(bs[1], Math.floor(goal.minutes), { key: `urc-today-${pid}-min` }); if (bs[2]) countUp(bs[2], sk, { key: `urc-today-${pid}-streak` });
    if (sk > 0) { const f = fx('streak_flame', { size: 28, loop: true, cls: 'flame-fx' }); hero.querySelector('.hh-flame .ic')?.replaceWith(f); if (ignite) setTimeout(() => retrigger(f, 'ignite', 0), 700); }
    // goal ring: fills from the last value shown today
    const fg = hero.querySelector('.rg-fg'), ringKey = `urc-ring-${pid}-${new Date().toDateString()}`; const prev = sGet(ringKey) ?? goal.frac; sSet(ringKey, goal.frac);
    if (fg) { fg.style.strokeDashoffset = String(100 - prev * 100); requestAnimationFrame(() => requestAnimationFrame(() => { fg.style.strokeDashoffset = String(100 - goal.frac * 100); })); }
    const g = hero.querySelector('.hh-goal');
    if (goal.done) { g.classList.add('reached'); g.querySelector('.hh-ring').append(fx('sparkles_loop', { size: 46, loop: true, cls: 'goal-fx' }));
      if (!sGet(goalFlag(pid))) { sSet(goalFlag(pid), 1); retrigger(g, 'goal-pop', 1200); setTimeout(() => { const say = hero.querySelector('.hh-say'), mk = hero.querySelector('.hh-marko'); if (!hero.isConnected || (say && say.dataset.keep)) return; if (say) { say.dataset.keep = '1'; say.innerHTML = `You reached today's goal, ${esc(profile.name)}!`; retrigger(say, 'say-pop', 0); } if (mk && mk._marko) setMarko(mk, 'cheer'); }, 900); } }
    // poke Marko
    const poke = hero.querySelector('.hh-poke'), stage = hero.querySelector('.hh-stage'); let lastPoke = 0, last = -1, restore;
    if (window.__memory?.line) window.__memory.line(profile).then(t => { const m = hero.querySelector('.hh-say .mem-line'); if (t && m && !m.closest('.hh-say').dataset.keep) m.textContent = t; }).catch(() => {});
    poke.onclick = () => { lastPoke = Date.now(); const mk = hero.querySelector('.hh-marko'), say = hero.querySelector('.hh-say'); const L = POKE(profile.name); let k; do k = Math.floor(Math.random() * L.length); while (k === last); last = k;
      if (say) { if (!say.dataset.orig) say.dataset.orig = say.innerHTML; say.dataset.keep = ''; say.textContent = L[k]; retrigger(say, 'say-pop', 0); clearTimeout(restore); restore = setTimeout(() => { if (say.isConnected) { say.innerHTML = say.dataset.orig; retrigger(say, 'say-pop', 0); } }, 3800); }
      if (mk) { if (mk._marko) setMarko(mk, Math.random() < .5 ? 'wave' : 'cheer'); retrigger(mk, 'poked', 600); }
      if (!rm) { const f = fx('stars_pop', { size: 110, cls: 'poke-fx' }); stage.append(f); setTimeout(() => f.remove(), 1600); }
      try { window.__feel?.chime?.(); } catch (e) {} };
    // an unprompted wave every ~12 s while Today is on screen and the tab is visible
    if (!rm) { const iv = setInterval(() => { if (!hero.isConnected) return clearInterval(iv); if (document.hidden || Date.now() - lastPoke < 5000) return; const mk = hero.querySelector('.hh-marko'); if (mk && mk._marko && mk._marko.state === 'idle') setMarko(mk, 'wave'); }, 12000); }
  }

  // Session: review due cards, then the next lesson step of the current unit, then one read.
  async function session() {
    const cur = await S.currentUnit(profile.id); st.unitN = cur; const sess = await S.startSession(profile.id); const started = Date.now();
    await header('Session', 'Review → lesson → read · about 10 minutes'); const bar = el('div', 'progress', '<i style="width:0"></i>'); main.append(bar);
    const box = el('div'); main.append(box); let step = 0; const steps = [];
    const due = await S.dueCards(profile.id, 12); if (due.length) steps.push(() => reviewCards(due, box, () => next()));
    const u = C.units[cur]; const p = await S.getProgress(profile.id); const done = p.units[cur]?.steps || {};
    if (u.letters.length && !done.hear) steps.push(() => { box.innerHTML = ''; box.append(el('h2', '', 'New letters')); u.letters.map(c => C.by[c]).filter(Boolean).forEach(l => box.append(D.letterCard(l, dctx))); box.append(nextBtn(() => { done.hear = true; next(); })); });
    if (u.letters.length && !done.tell) steps.push(() => { box.innerHTML = ''; box.append(D.tellApart(u, dctx, (sc) => { done.tell = sc >= 7; box.append(nextBtn(next)); })); });
    if (u.words.length && !done.join) steps.push(() => { box.innerHTML = ''; box.append(D.joinIt(u, dctx, marks, () => { done.join = true; box.append(nextBtn(next)); })); });
    if (u.words.length) steps.push(() => { box.innerHTML = ''; box.append(D.readIt(u, dctx, marks)); box.append(nextBtn(next)); });
    if (u.letters.length && !done.write && profile.track !== 'adult') steps.push(() => { box.innerHTML = ''; box.append(D.writeIt(u, dctx, styleName, () => { done.write = true; })); box.append(nextBtn(next)); });
    if (u.words.length && !done.dict) steps.push(() => { box.innerHTML = ''; box.append(D.dictation(u, dctx, marks, (sc) => { done.dict = sc >= 4; box.append(nextBtn(next)); })); });
    if (u.words.length && !p.units[cur]?.passed) steps.push(() => { box.innerHTML = ''; box.append(D.quiz(u, dctx, marks, async (sc, t) => { const passed = await S.markUnit(profile.id, cur, sc, t); if (passed) { toast('Unit ' + cur + ' passed!'); await S.ensureCards(profile.id, cur + 1); } box.append(nextBtn(next)); })); });
    if (cur === 11) steps.push(() => { box.innerHTML = ''; box.append(unit11()); box.append(sightDrill()); box.append(nextBtn(next)); });
    if (u.sentences.length) steps.push(() => fluency(u, box, () => next()));
    if (cur === 0) steps.unshift(() => { box.innerHTML = ''; box.append(el('div', 'card', `<h2>Five things before letter one</h2><ol style="padding-left:18px"><li><b>Right to left.</b> The first letter is on the right.</li><li><b>Letters join</b> like cursive and change shape. Ten never join forward: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span></li><li><b>Dots decide the letter.</b> <span class="ur">ب پ ت ٹ ث ن ی</span> share one body.</li><li><b>Small marks are vowels.</b> We keep them until unit 11.</li><li><b>Two typefaces</b>, Naskh for learning and Nastaliq for print.</li></ol>`)); box.append(unit0()); box.append(nextBtn(next)); });
    if (cur === 0) steps.push(() => { box.innerHTML = ''; box.append(el('div', 'card', '<h2>Unit 0 done</h2><p>You know the five rules. Unit 1 starts with <span class="ur">ا ب ک ل م ن</span>.</p>')); S.markUnit(profile.id, 0, 10, 10).then(() => S.ensureCards(profile.id, 1)); box.append(nextBtn(next)); });
    async function next() { const pr = await S.getProgress(profile.id); pr.units[cur] = { ...(pr.units[cur] || {}), steps: done }; await db.put('progress', pr); step++; bar.firstChild.style.width = Math.min(100, step / Math.max(1, steps.length) * 100) + '%'; if (step >= steps.length) return finish(); steps[step](); }
    async function finish() { sess.bites = step; await S.endSession(sess); burst(); const mins = Math.round((Date.now() - started) / 60000); box.innerHTML = ''; box.append(el('div', 'card hero', `${confetti()}${profile.track === 'child' ? mascot('cheer', 150) : `<span class="ic" style="font-size:56px;color:var(--good)">${icon('check')}</span>`}<h2>Session done</h2><div class="muted">${step} bites in ${mins} min</div>`)); const b = el('button', 'btn btn-primary btn-wide', 'Back to Today'); b.onclick = () => { st.tab = 'today'; render(); }; box.append(b); }
    if (!steps.length) return finish(); steps[0]();
  }
  async function placement() { main.innerHTML = ''; await header('Placement check', 'Tap what you hear, then the word you hear. We stop at the first unit that is not yet solid.'); const box = el('div'); main.append(box); let n = 1;
    const taughtPool = k => C.units.filter(u => u.n <= k).flatMap(u => u.letters).filter(c => C.by[c]);
    // each stage asks every letter of the unit once plus one word; one miss ends the check (a unit is "known" only if all of it is)
    function stage() { const u = C.units[n]; if (!u || !u.letters.length) return finish(n - 1); box.innerHTML = ''; box.append(el('h2', '', `Unit ${n} letters`)); const items = D.placementItems(u, taughtPool(n), marks); const status = el('div', 'score'), choices = el('div', 'choices'); let k = 0, cur, locked = false; box.append(D.sayRow(D.sayBtn(() => cur && play(cur.audio)), status), choices);
      function next() { if (k >= items.length) { n++; return stage(); } cur = items[k++]; locked = false; status.textContent = `Question ${k} of ${items.length}`; choices.innerHTML = ''; cur.options.forEach(o => { const t = el('button', 'tile ur' + (cur.kind === 'word' ? ' small' : ''), o.text); t.setAttribute('aria-label', o.label); if (o.right) t.dataset.right = cur.audio; t.onclick = () => { if (locked) return; locked = true; if (o.right) { t.classList.add('ok'); setTimeout(next, 400); } else { t.classList.add('no'); setTimeout(() => finish(n - 1), 700); } }; choices.append(t); }); play(cur.audio); }
      next(); }
    async function finish(passedUpTo) { try { await finish2(passedUpTo); } catch (e) { box.innerHTML = ''; const rb = el('button', 'btn btn-primary btn-wide', 'Try again'); rb.onclick = () => { if (tapLock()) finish(passedUpTo); }; box.append(el('div', 'card center', '<h2>That did not save yet</h2><p class="muted">The phone could not save your result. Nothing is lost.</p>'), rb); } }
    async function finish2(passedUpTo) { document.querySelectorAll('.feel-say').forEach(x => x.remove()); for (let k = 0; k <= passedUpTo; k++) await S.markUnit(profile.id, k, 10, 10); await S.ensureCards(profile.id, passedUpTo + 1); box.innerHTML = ''; box.append(el('div', 'card hero', `<h2>Start at unit ${passedUpTo + 1}</h2><div class="muted">${passedUpTo > 0 ? `Units 1–${passedUpTo} marked as known.` : 'Start from the beginning.'}</div>`)); const b = el('button', 'btn btn-primary btn-wide dock', 'Go'); b.onclick = () => { st.tab = 'today'; render(); }; box.append(b); }
    stage(); }
  async function parentReport() { const s = await S.stats(profile.id); const a = (await db.by('assessments', 'profileId', profile.id)).sort((x, y) => y.ts - x.ts)[0]; const cur = await S.currentUnit(profile.id); const lines = [`${profile.name} · Urdu Qaida report · ${new Date().toLocaleDateString()}`, `Unit ${cur} of 12 (${s.unitsPassed} passed) · ${s.sessions} sessions`, `Letters solid: ${s.lettersMastered}/${s.letters} · Words solid: ${s.wordsMastered}/${s.words}`, s.wpm.length ? `Reading speed: ${s.wpm[s.wpm.length - 1].wpm} words/min (60 meets grade-2)` : 'Reading speed: not measured yet', a ? `Last assessment: ${new Date(a.ts).toLocaleDateString()}, ${a.orfDone === false ? 'passage not tested' : (a.orf?.cwpm ?? '-') + ' cwpm, ' + recBand(a)}` : '', `Next: 10 minutes a day, ${s.due} cards due. Ask ${profile.name} to read the unit ${cur} words aloud to you.`].filter(Boolean).join('\n');
    main.innerHTML = ''; await header('Parent report'); const c = el('div', 'card'); c.innerHTML = `<pre style="white-space:pre-wrap;font:inherit;margin:0;overflow-wrap:anywhere">${esc(lines)}</pre>`; const sh = el('button', 'btn btn-primary btn-wide dock', `${icon('share')} Share`); sh.onclick = async () => { try { if (navigator.share) await navigator.share({ text: lines }); else { await navigator.clipboard.writeText(lines); toast('Copied'); } } catch (e) {} }; const back = el('button', 'btn', 'Back'); back.onclick = () => { st.tab = 'today'; render(); }; c.append(el('div', 'row', ''), sh, back); main.append(c); }
  const nextBtn = fn => { const b = el('button', 'btn btn-primary btn-wide', 'Next'); b.onclick = fn; b.style.marginTop = '10px'; return b; };

  function reviewCards(cards, box, onDone) {
    let i = 0, right = 0; box.innerHTML = ''; const head = el('h2', '', `${cards.length} ${cards.length === 1 ? 'card' : 'cards'} to review`), card = el('div', 'card center'), ctr = el('div', 'muted'); box.append(head, ctr, card);
    const dk = el('div', 'dock-row'); function show() { dk.innerHTML = ''; if (i >= cards.length) { dk.remove(); toast(`${right}/${cards.length} remembered`); onDone(); return; } const c = cards[i]; ctr.textContent = `${i + 1} / ${cards.length}`; card.innerHTML = `<div class="ur big">${esc(c.v || c.item)}</div>`;
      const sub = el('div', 'muted', c.kind === 'letter' ? 'Say the letter name and sound, then check' : 'Read the word aloud, then check'); const hear = D.sayBtn(() => play(S.audioKeyFor(c)), 'Hear it');
      const reveal = el('div', 'muted', ''); const got = el('button', 'btn btn-primary btn-wide', 'Got it'), miss = el('button', 'btn btn-wide', 'Not yet');
      let busy = false; /* one grade per card: a burst of taps never grades two cards */ got.onclick = async () => { if (busy || !tapLock()) return; busy = true; try { await S.gradeCard(c, true); } catch (e) { busy = false; return toast('Could not save that answer. Try again.'); } right++; i++; show(); }; miss.onclick = async () => { if (busy || !tapLock()) return; busy = true; try { await S.gradeCard(c, false); } catch (e) { busy = false; return toast('Could not save that answer. Try again.'); } reveal.textContent = c.kind === 'letter' ? `${C.by[c.item].name} — ${C.by[c.item].hint}` : `${c.rom || ''} ${c.en ? '— ' + c.en : ''}`; play(S.audioKeyFor(c)); setTimeout(() => { i++; show(); }, 1400); };
      card.append(D.sayRow(hear), sub, reveal); dk.append(miss, got); box.append(dk); }
    show();
  }

  function fluency(u, box, onDone, usePassage) {
    box.innerHTML = ''; const sents = usePassage ? [W(u.passage)] : u.sentences.map(W); const text = sents.map(s => marks() ? s.v : s.ur).join(' '); const words = text.split(' ').length;
    box.append(el('h2', '', 'Read for speed')); const p = el('div', 'card'); p.innerHTML = `<div class="ur" style="font-size:${usePassage ? 26 : 30}px;text-align:right">${text}</div>${usePassage ? `<div class="muted">${sents[0].en}</div>` : ''}<div class="muted">${words} words. Tap Start, read aloud, tap Stop. Read it twice.</div>`;
    const t = el('div', 'timer', '0.0 s'), start = el('button', 'btn btn-gold', `${icon('timer')} Start`), stop = el('button', 'btn', 'Stop'), res = el('div', 'score'); let t0, h; stop.disabled = true;
    start.onclick = () => { t0 = Date.now(); start.disabled = true; stop.disabled = false; h = setInterval(() => t.textContent = ((Date.now() - t0) / 1000).toFixed(1) + ' s', 100); };
    stop.onclick = async () => { clearInterval(h); const sec = (Date.now() - t0) / 1000; const wpm = Math.round(words * 60 / sec); const prev = (await S.stats(profile.id)).wpm; const best = Math.max(0, ...prev.map(x => x.wpm)); res.textContent = `${wpm} words per minute${wpm > best ? ' · new personal best!' : best ? ` · best ${best}` : ''}`; try { await S.addWpm(profile.id, wpm, u.n); } catch (e) { toast('Your speed did not save. You can try again.'); } start.disabled = false; stop.disabled = true; start.innerHTML = `${icon('timer')} Again`; };
    const row = el('div', 'row'); row.append(start, stop); if (!usePassage) sents.forEach((s, i) => row.append(D.playBtn(sentKey(u.n, i), true))); p.append(t, row, res); box.append(p, nextBtn(onDone));
  }

  async function units() { await header('Units', 'Tap a unit to open its lesson'); if (kid()) { const bk = el('button', 'btn btn-chip', `${icon('back')} Back to Learn`); bk.onclick = () => { st.tab = 'today'; render(); }; main.insertBefore(bk, main.firstChild); } const p = await S.getProgress(profile.id); const cur = await S.currentUnit(profile.id);
    const libBtn = el('button', 'btn btn-wide', 'Letter library · all 38 letters'); libBtn.onclick = () => document.getElementById('library')?.scrollIntoView({ behavior: 'smooth' }); main.append(libBtn);
    const g = el('div', 'unitgrid'); C.units.forEach(u => { const b = el('button', 'ucard ' + (p.units[u.n]?.passed ? 'done ' : '') + (u.n === cur ? 'cur ' : '') + (u.n > cur ? 'locked' : ''), `<span class="pill">${u.n > cur ? icon('lock') + ' ' : ''}Unit ${u.n}</span>${unitArt(u.n)}<b>${u.title}</b><span class="ur muted" style="font-size:18px">${u.letters.join(' ')}</span>${u.n > cur ? `<span class="uc-peek">${mascot(u.n === cur + 1 ? 'point' : 'think', 72)}</span>` : ''}`); b.title = u.title; b.setAttribute('aria-label', `Unit ${u.n}, ${u.title}${u.n > cur ? ', locked' : ''}`); b.onclick = () => { st.unitN = u.n; st.tab = 'lesson'; render(); }; /* a locked unit opens as a read-only preview (see lesson()) */ g.append(b); }); main.append(g);
    const lh = el('h3', '', 'Letter library · dictionary order'); lh.id = 'library'; main.append(lh); const lib = el('div', 'choices'); lib.style.justifyContent = 'flex-start'; 'ا ب پ ت ٹ ث ج چ ح خ د ڈ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ہ ھ ئ ی ے'.split(' ').forEach(ch => { const l = C.by[ch]; if (!l) return; const t = el('button', 'tile small ur', ch); t.title = l.name; t.onclick = () => { play('names/' + l.id); const d = document.getElementById('libcard'); d.innerHTML = ''; d.append(D.letterCard(l, dctx)); d.scrollIntoView({ behavior: 'smooth', block: 'start' }); }; lib.append(t); }); main.append(lib); const lc = el('div', '', ''); lc.id = 'libcard'; main.append(lc); }

  async function lesson() { const un = Number.isInteger(st.unitN) && st.unitN >= 0 && st.unitN < C.units.length ? st.unitN : 0; const u = C.units[un]; const curU = await S.currentUnit(profile.id); const preview = u.n > curU; st.preview = preview; const dc = preview ? { ...dctx, record: () => {} } : dctx; // preview: nothing is recorded, no cards, no pass
    await header(`Unit ${u.n} · ${u.title}`, u.focus); if (preview) main.append(el('div', 'card preview-note', `<b>Preview only.</b> Finish unit ${curU} to open unit ${u.n}. Nothing you do here is saved.`)); main.append(el('div', 'ur', u.title_ur));
    if (u.letters.length) { main.append(el('h3', '', '1 · Hear and see')); u.letters.map(c => C.by[c]).filter(Boolean).forEach(l => main.append(D.letterCard(l, dc))); }
    if (u.n === 6) main.append(aspirates()); if (u.n === 0) { main.append(unit0()); main.append(punctuation()); } if (u.n === 10) { main.append(izafat()); main.append(punctuation()); } if (u.n === 11) { main.append(unit11()); main.append(sightDrill()); } if (u.n === 4) main.append(el('div', 'card', '<h2>Guess before you look</h2><p>Build <span class="ur">دور</span> <i>dūr</i> and <span class="ur">ہار</span> <i>hār</i> from tiles first. Which letters made the next letter start fresh? Then check the forms: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span> never join forward. You discovered the rule instead of being told it.</p>'));
    if (u.letters.length) { main.append(el('h3', '', '3 · Tell it apart <span class="pill">recognition · self-check</span>')); main.append(D.tellApart(u, dc)); }
    [[D.joinIt, '4 · Join it <span class="pill">production · self-check</span>'], [D.readIt, '5 · Read it <span class="pill">reading aloud · audio check</span>']].forEach(([f, t]) => { const x = f(u, dc, marks); if (x) { main.append(el('h3', '', t)); main.append(x); } });
    if (u.letters.length) { main.append(el('h3', '', '6 · Write it <span class="pill">production · tracer check</span>')); main.append(D.writeIt(u, dc, styleName)); }
    const d = D.dictation(u, dc, marks); if (d) { main.append(el('h3', '', '7 · Dictation <span class="pill">production · self-check</span>')); main.append(d); }
    const q = preview ? null : D.quiz(u, dc, marks, async (sc, t) => { const passed = await S.markUnit(profile.id, u.n, sc, t); if (passed) { toast('Unit ' + u.n + ' passed!'); await S.ensureCards(profile.id, u.n + 1); } }); if (q) { main.append(el('h3', '', '8 · Check <span class="pill">recognition · gate</span>')); main.append(q); }
    if (u.n === 12 && !preview) main.append(selfTest());
  }
  function aspirates() { const c = el('div', 'card'); c.innerHTML = '<h2>Aspirates and the nasal vowel</h2><p class="muted">Write ھ after a consonant for a puff of breath (بھ پھ کھ گھ). ں nasalises the vowel before it.</p>'; const t = el('div', 'table'); t.innerHTML = `<table>${C.letters.aspirates.map((a, i) => `<tr><td class="ur" style="font-size:26px">${a[0]}</td><td>${a[1]}</td><td class="ur" style="font-size:24px">${a[2]}</td><td>${a[3]} — ${a[4]}</td><td id="asp-${i}"></td></tr>`).join('')}</table>`; c.append(t); C.letters.aspirates.forEach((a, i) => { const b = D.playBtn('aspirates/' + a[1], true); b.setAttribute('aria-label', 'Play ' + a[1]); c.querySelector('#asp-' + i)?.append(b); }); return c; }
  function punctuation() { const c = el('div', 'card'); c.innerHTML = `<h2>Punctuation and numerals</h2><div class="table"><table>${C.letters.punctuation.map(x => `<tr><td class="ur" style="font-size:26px">${x[0]}</td><td>${x[2]}</td><td class="muted">${x[1]}</td></tr>`).join('')}</table></div><p class="muted">The full stop is a short line (۔), the comma is upside-down (،), the question mark is mirrored (؟). Numerals run left to right even inside Urdu text.</p><div class="grid-words">${C.letters.numerals.map(x => `<span>${x[0]}<small style="font-size:12px;color:var(--muted)"> ${x[1]}</small></span>`).join('')}</div>`; return c; }
  function izafat() { const z = C.letters.izafat; const c = el('div', 'card'); c.innerHTML = `<h2>Iẕāfat</h2><p>${z.explain}</p><div class="table"><table>${z.examples.map(e => `<tr><td class="ur" style="font-size:26px">${e[0]}</td><td>${e[1]}</td><td>${e[2]}</td></tr>`).join('')}</table></div>`; return c; }
  function unit0() { const c = el('div', 'card'); c.innerHTML = `<h2>Vowel marks</h2><p class="muted">Same three letters, three words: <span class="ur">گَل</span> gal (cheek) · <span class="ur">گِل</span> gil (clay) · <span class="ur">گُل</span> gul (flower).</p><div class="table"><table>${C.letters.diacritics.map(x => `<tr><td class="ur" style="font-size:26px">بـ${x.ch}</td><td>${x.name}</td><td>${x.sound}</td><td class="ur" style="font-size:22px">${x.example[0]}</td><td>${x.example[1]} — ${x.example[2]}</td><td id="d-${x.id}"></td></tr>`).join('')}</table></div><h3>Long vowels</h3><div class="table"><table>${C.letters.long_vowels.map(x => `<tr><td class="ur" style="font-size:24px">${x[0]}</td><td>${x[1]}</td><td class="ur" style="font-size:22px">${x[2].split(' ')[0]}</td><td>${x[2].split(' ').slice(1).join(' ')}</td></tr>`).join('')}</table></div><h3>Numerals</h3><div class="grid-words">${C.letters.numerals.map(x => `<span>${x[0]}<small style="font-size:12px;color:var(--muted)"> ${x[1]}</small></span>`).join('')}</div>`; C.letters.diacritics.forEach(x => c.querySelector('#d-' + x.id).append(D.playBtn('diacritics/' + x.id, true), D.playBtn('diacritics/' + x.id + '_ex', true))); return c; }
  function sightDrill() { const box = el('div', 'card'); box.innerHTML = '<h2>Tell the sight words apart</h2><p class="muted">Tap the word you hear · 10 rounds</p>'; const sw = C.letters.sight_words; const status = el('div', 'score'), choices = el('div', 'choices'), btn = el('button', 'btn btn-primary', 'Play word'); let round = 0, score = 0, target;
    function next() { if (round >= 10) { status.textContent = `Done: ${score}/10`; choices.innerHTML = ''; btn.textContent = 'Again'; btn.onclick = () => { round = 0; score = 0; next(); }; return; } round++; target = Math.floor(Math.random() * sw.length); status.textContent = `Round ${round}/10 · ${score} right`; choices.innerHTML = '';
      shuffle([target, ...shuffle(sw.map((w, i) => i).filter(i => i !== target)).slice(0, 5)]).forEach(i => { const t = el('button', 'tile small ur', sw[i]); t.onclick = () => { const ok = i === target; dctx.record('sight', sw[target], ok, 0); if (ok) { t.classList.add('ok'); score++; setTimeout(next, 450); } else { t.classList.add('no'); play('sight/' + String(i).padStart(2, '0')); } }; choices.append(t); });
      play('sight/' + String(target).padStart(2, '0')); btn.textContent = 'Play again'; btn.onclick = () => play('sight/' + String(target).padStart(2, '0')); }
    btn.onclick = next; box.append(status, btn, choices); return box; }
  function unit11() { const c = el('div', 'card'); c.innerHTML = '<h2>Sight words</h2><p class="muted">These twenty are a third of any Urdu text.</p>'; const g = el('div', 'words'); C.letters.sight_words.forEach((w, i) => { const d = el('div', 'word', `<div class="ur">${w}</div>`); d.append(D.playBtn('sight/' + String(i).padStart(2, '0'), true)); d.onclick = () => play('sight/' + String(i).padStart(2, '0')); g.append(d); }); c.append(g); c.insertAdjacentHTML('beforeend', `<h3>Naskh → Nastaliq</h3><div class="row">${['کتاب', 'پڑھنا', 'میں گھر میں ہوں'].map(w => `<div class="card" style="margin:0;text-align:center"><div class="ur" style="font-family:var(--naskh)">${w}</div><div class="ur nastaliq">${w}</div></div>`).join('')}</div><h3>Dictionary order</h3><div class="grid-words" style="font-size:26px">${'ا ب پ ت ٹ ث ج چ ح خ د ڈ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ہ ھ ء ی ے'.split(' ').map(x => `<span>${x}</span>`).join('')}</div><p class="muted">Turn vowel marks off in More and re-read earlier units.</p>`); return c; }

  async function review() { await header('Review', 'Letters and words that are about to slip'); const due = await S.dueCards(profile.id, 30); if (!due.length) { const [pl, sk, cur] = await Promise.all([S.pearls(profile.id), S.streak(profile.id), S.currentUnit(profile.id)]); const c = el('div', 'night', `<div class="night-moon"></div><div class="fx-stage">${mascot('sleep', 170)}</div><h2>All caught up</h2><p>Marko is resting. Your letters come back for review when they are about to slip, so there's nothing to do here today.</p><div class="night-stats"><div><b>${pl}</b><small>pearls</small></div><div><b>${sk}</b><small>days practised</small></div></div>`); c.querySelector('.fx-stage').prepend(fx('sleeping_zzz', { size: 80, loop: true, cls: 'fx-zz' })); main.append(c);
      const nx = el('div', 'card row next-up', `${unitArt(cur)}<div style="flex:1"><small class="muted">Next up</small><b>Unit ${cur}: ${C.units[cur].title}</b></div>`); const go = el('button', 'btn btn-primary btn-wide dock', `Learn: unit ${cur}`); go.onclick = () => { st.tab = 'today'; render(); }; main.append(go); main.insertBefore(nx, go); return; } const box = el('div'); main.append(box); reviewCards(due, box, () => { st.tab = 'today'; render(); }); }

  async function read() { await header('Read', 'Passages and sentences · read twice, watch your speed'); const cur = await S.currentUnit(profile.id);
    C.units.filter(u => u.passage && u.n <= Math.max(cur, 1)).reverse().forEach(u => { const box = el('div'); main.append(el('h3', '', `Passage · unit ${u.n}`)); main.append(box); fluency(u, box, () => {}, true); box.lastChild.remove(); });
    C.units.filter(u => u.sentences.length && u.n <= Math.max(cur, 1)).reverse().forEach(u => { const box = el('div'); main.append(el('h3', '', `Sentences · unit ${u.n}`)); main.append(box); fluency(u, box, () => {}); box.lastChild.remove(); }); }

  async function progress(noHead) { if (!noHead) await header('Progress'); main.append(await renderDashboard(profile.id, { child: profile.track === 'child' })); }
  // Me (child track): progress first, then everything that lives in More for the other tracks.
  // Practice PDFs (printable): a regular button, never a second primary action
  const practiceEntry = () => {
    const c = el('div', 'card practice-entry', `<div class="row" style="flex-wrap:nowrap"><span class="mode-ic">${icon('book')}</span><div style="flex:1"><b>Practice sheets</b><div class="muted">Printable PDFs for each unit: tracing, reading, dictation and answer keys</div></div></div>`);
    const b = el('button', 'btn btn-wide', `${icon('book')} Open practice sheets`);
    b.onclick = () => openPractice({ unit: Math.max(1, st.unitN || 1) });
    c.append(b); return c;
  };
  async function me() { await header('Me'); const [pl, sk, cur] = await Promise.all([S.pearls(profile.id), S.streak(profile.id), S.currentUnit(profile.id)]);
    main.append(el('div', 'card me-card', `<div class="me-id">${avatar(profile, 64)}<div><b>${esc(profile.name)}</b><small class="muted">Unit ${cur}${C.units[cur] ? ' · ' + C.units[cur].title : ''}</small></div>${mascot('proud', 92, 'me-marko')}</div><div class="me-stats"><div style="--c:var(--gold-deep)">${icon('star')}<b class="cu">${pl}</b><small>${pl === 1 ? 'pearl' : 'pearls'}</small></div><div class="me-flame" style="--c:var(--coral)">${icon('flame')}<b class="cu">${sk}</b><small>days practised</small></div><div style="--c:var(--accent)">${icon('units_f')}<b class="cu">${Math.max(0, cur)}</b><small>units done</small></div></div>`));
    const me$ = main.querySelector('.me-stats'); if (me$) { const [a, b, c] = me$.querySelectorAll('b.cu'); countUp(a, pl, { key: `urc-me-${profile.id}-pearls` }); countUp(b, sk, { key: `urc-me-${profile.id}-streak` }); countUp(c, Math.max(0, cur), { key: `urc-me-${profile.id}-units` }); if (sk > 0) me$.querySelector('.me-flame .ic')?.replaceWith(fx('streak_flame', { size: 28, loop: true, cls: 'flame-fx' })); }
    main.append(practiceEntry()); await progress(true); main.append(el('h3', 'me-h3', 'Settings and more')); await more(true); }

  function selfTest() { const c = el('div', 'card'); c.innerHTML = '<h2>Test yourself</h2><p class="muted">Five parts, like the teacher\'s assessment. This is your reading speed today, not a certificate.</p>'; const b = el('button', 'btn btn-primary', 'Start the reading test'); b.onclick = () => { st.tab = 'test'; render(); }; c.append(b); return c; }
  async function test() { await header('Test yourself', 'Five parts · a helper times you, or use the timer'); const A = C.letters.assessment; const results = {};
    const part = (title, items, key, secs) => { const c = el('div', 'card'); c.innerHTML = `<h2>${title}</h2><p class="muted">Tap Start, read aloud right to left, tap the ones you got wrong. Stop at ${secs} s.</p>`; const g = el('div', 'grid-words'); const wrong = new Set(); items.forEach((it, i) => { const s = el('span', 'item ur', it); s.onclick = () => { wrong.has(i) ? wrong.delete(i) : wrong.add(i); s.classList.toggle('wrong'); }; g.append(s); });
      const t = el('div', 'timer', String(secs)), start = el('button', 'btn btn-primary', 'Start'), res = el('div', 'score'); let t0, h; start.onclick = () => { t0 = Date.now(); start.disabled = true; h = setInterval(() => { const left = secs - (Date.now() - t0) / 1000; t.textContent = Math.max(0, left).toFixed(0); if (left <= 0) { clearInterval(h); const n = Math.min(items.length, parseInt(prompt('How many did you reach?', String(items.length))) || 0); const score = n - [...wrong].filter(i => i < n).length; results[key] = score; res.textContent = `${score} correct per minute`; S.recordAttempt(profile.id, 12, 'self-' + key, key, true, score); start.disabled = false; } }, 250); }; c.append(t, start, g, res); return c; };
    main.append(part('1 · Letter sounds', shuffle(C.letters.letters.concat(C.letters.letters)).slice(0, 60).map(l => l.ch), 'letters', 60));
    main.append(part('2 · Nonwords', shuffle(A.nonwords.concat(A.nonwords)).slice(0, 30), 'nonwords', 60));
    main.append(part('3 · Familiar words', shuffle(C.units.flatMap(u => u.words.map(w => w[0]))).slice(0, 40), 'words', 60));
    const pc = el('div', 'card'); pc.innerHTML = `<h2>4 · Passage</h2><div class="ur" style="font-size:26px;text-align:right">${A.passage}</div>`; const words = A.passage.split(' ').length; const t = el('div', 'timer', '0.0 s'), start = el('button', 'btn btn-primary', 'Start'), stop = el('button', 'btn', 'Stop'), errs = el('input'), res = el('div', 'score'); errs.type = 'number'; errs.min = 0; errs.value = 0; errs.style.width = '80px'; let t0, h; stop.disabled = true;
    start.onclick = () => { t0 = Date.now(); start.disabled = true; stop.disabled = false; h = setInterval(() => t.textContent = ((Date.now() - t0) / 1000).toFixed(1) + ' s', 100); };
    stop.onclick = async () => { clearInterval(h); const sec = (Date.now() - t0) / 1000; if (sec < 15) { res.textContent = 'That was too quick to count. Tap Start and read the whole passage.'; start.disabled = false; stop.disabled = true; return; } const cwpm = Math.min(200, Math.round(Math.max(0, words - (+errs.value || 0)) * 60 / sec)); results.cwpm = cwpm; const lvl = cwpm > 90 ? 'exceeds the grade-2 standard' : cwpm >= 60 ? 'meets the standard' : cwpm > 0 ? 'below the standard: repeat the units the earlier parts flagged' : 'nonreader: restart at unit 1'; res.textContent = `${cwpm} cwpm — ${lvl}`; await S.addWpm(profile.id, cwpm, 12); await db.put('assessments', { id: uid(), profileId: profile.id, ts: Date.now(), letters: results.letters, nonwords: results.nonwords, words: results.words, orf: { cwpm, seconds: Math.round(sec), errors: +errs.value || 0 }, band: bandFor(cwpm), by: 'self' }); start.disabled = false; stop.disabled = true; };
    const row = el('div', 'row'); row.append(start, stop, el('span', 'muted', 'errors:'), errs); pc.append(t, row, res); main.append(pc);
    const qc = el('div', 'card'); qc.innerHTML = `<h2>5 · Comprehension</h2><ol style="padding-left:18px">${A.questions.map(q => `<li class="ur" style="font-size:22px;text-align:right">${q}</li>`).join('')}</ol><details><summary>Answer key</summary><ol style="padding-left:18px">${A.answers.map(a => `<li>${a}</li>`).join('')}</ol></details><div class="table" style="margin-top:8px"><table><tr><th>cwpm</th><th>Level</th></tr><tr><td>&gt; 90</td><td>exceeds grade-2 standard</td></tr><tr><td>60–90</td><td>meets standard</td></tr><tr><td>1–59</td><td>below standard</td></tr><tr><td>0</td><td>nonreader</td></tr></table></div>`; main.append(qc); }

  async function more(noHead) { if (!noHead) { await header('More'); main.append(practiceEntry()); } const c = el('div', 'card'); c.innerHTML = '<h2>Settings</h2>';
    const track = sel(['child', 'adult', 'heritage'], ['Child (5–10)', 'Adult, new to Urdu', 'Speaks Urdu, can\'t read'], profile.track, async v => { profile.track = v; await db.put('profiles', profile); ctx.apply(); });
    const style = sel(['naskh', 'nastaliq'], ['Naskh (learning)', 'Nastaliq (print)'], ctx.settings.style || 'naskh', v => ctx.set('style', v));
    const marksCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.marks !== false ? 'checked' : ''}> Show vowel marks (until unit 10)`); marksCb.querySelector('input').onchange = e => ctx.set('marks', e.target.checked);
    const size = sel(['1', '1.25', '1.5'], ['Normal text', 'Large', 'Extra large'], String(ctx.settings.scale || '1'), v => ctx.set('scale', v));
    const romCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.rom === false ? '' : 'checked'}> Show romanisation (Latin letters)`); romCb.querySelector('input').onchange = e => ctx.set('rom', e.target.checked);
    const aoCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.audioOnly ? 'checked' : ''}> Audio-first mode (words hidden until tapped)`); aoCb.querySelector('input').onchange = e => ctx.set('audioOnly', e.target.checked);
    const sp = sel(['0', '0.05', '0.12'], ['Normal letter spacing', 'Wider', 'Widest (dyslexia-friendly)'], String(ctx.settings.spacing || '0'), v => ctx.set('spacing', v));
    c.append(lab('Track', track), lab('Script', style), lab('Text size', size), lab('Letter spacing', sp), marksCb, romCb, aoCb); main.append(c);
    const d = el('div', 'card'); d.innerHTML = '<h2>Data</h2><p class="muted">Everything stays on this phone. Export to keep a backup or move to another phone.</p>'; const ex = el('button', 'btn', 'Export backup (JSON)'); ex.onclick = () => ctx.exportBackup(); const im = el('input'); im.type = 'file'; im.accept = '.json'; im.onchange = e => { const f = e.target.files[0]; e.target.value = ''; restoreFromFile(f, { onDone: () => render() }); }; const reset = el('button', 'btn btn-danger', 'Reset this profile\'s progress'); reset.onclick = async () => { if (!await askGrownup({ title: 'Reset progress?', note: 'This deletes all progress for ' + profile.name + ' and cannot be undone. Grown-ups only.' })) return; try { for (const s of ['cards', 'attempts', 'sessions', 'assessments']) for (const r of await db.by(s, 'profileId', profile.id)) await db.del(s, r.id); await db.del('progress', profile.id); await db.del('settings', 'stickersSeen:' + profile.id); } catch (e) { return toast('Reset could not finish. Nothing more was changed. Try again.'); } toast('Reset'); st.tab = 'today'; render(); }; im.hidden = true; const imb = el('button', 'btn', 'Restore from a backup'); imb.onclick = async () => { if (await askGrownup({ title: 'Import a backup', note: 'Importing adds the learners from a backup file. Grown-ups only, please.' })) im.click(); }; d.append(el('div', 'row', ''), ex, imb, im, reset); main.append(d);
    const sw = el('button', 'btn btn-wide', 'Switch profile / mode'); sw.onclick = ctx.switchProfile; main.append(sw);
    // Contribute: email for fixes and help, bank transfer for optional support. Every external action sits behind the grown-up gate.
    const EMAIL = 'oyekamalkhan@gmail.com';
    const ct = el('div', 'card'); ct.innerHTML = `<h2>${icon('sparkle')} Help make this better</h2><p class="muted">Urdu Qaida is free and made by one person in Pakistan. Found a wrong sound, a bug, or a missing word? Want to record a real voice, translate, or teach with it? Write to Kamal.</p>`;
    const copyText = async (text, okMsg, node) => { try { await navigator.clipboard.writeText(text); toast(okMsg); } catch (e) { try { const r = document.createRange(); r.selectNodeContents(node); const sl = getSelection(); sl.removeAllRanges(); sl.addRange(r); toast('Selected. Press and hold to copy.'); } catch (e2) { toast(text); } } };
    const addr = el('div', 'contact-addr', ''); addr.hidden = true; addr.innerHTML = '<div class="muted">Kamal\'s email</div>'; const addrText = el('span', 'contact-mail', EMAIL); addrText.style.userSelect = 'all'; addr.append(addrText);
    const em = el('button', 'btn btn-wide', `${icon('share')} Email Kamal`); em.onclick = async () => { if (!await askGrownup({ title: 'Email Kamal', note: 'This opens your email app. Grown-ups only, please.' })) return; addr.hidden = false; const url = `mailto:${EMAIL}?subject=Urdu%20Qaida`; try { window.open(url, '_system'); } catch (e) { location.href = url; } };
    const cpm = el('button', 'btn btn-wide', `${icon('share')} Copy email address`); cpm.onclick = async () => { if (!await askGrownup({ title: 'Copy email address', note: 'Grown-ups only, please.' })) return; addr.hidden = false; await copyText(EMAIL, 'Address copied', addrText); };
    const dn = el('button', 'btn btn-gold btn-wide', `${icon('star')} Support Urdu Qaida`); const dcard = el('div', 'card donate-card', ''); dcard.hidden = true; dcard.style.background = 'var(--soft)';
    const BANK = [['Bank', 'HBL'], ['Account title', 'MUHAMMAD KAMAL'], ['Account number', '22927917193503', 1], ['IBAN', 'PK64HABB0022927917193503', 1], ['Branch', 'NUST Branch, Islamabad']];
    dn.onclick = async () => { if (!await askGrownup({ title: 'Support Urdu Qaida', note: 'Bank details for an optional gift. Grown-ups only, please.' })) return;
      dcard.hidden = false; dcard.innerHTML = '<b>Support Urdu Qaida</b><p class="muted">Entirely optional. Urdu Qaida stays free and ad-free whether or not you give. If you would like to help with the costs of making it, you can send a bank transfer to the account below. Thank you, from one person in Pakistan.</p>';
      const rows = el('div', 'donate-rows');
      BANK.forEach(([k, v, canCopy]) => { const r = el('div', 'donate-row'); const t = el('div', 'donate-kv'); t.append(el('span', 'donate-k muted', k)); const vv = el('span', 'donate-v', v); vv.style.userSelect = 'all'; t.append(vv); r.append(t);
        if (canCopy) { const b = el('button', 'btn btn-chip', 'Copy'); b.setAttribute('aria-label', `Copy ${k}`); b.onclick = () => copyText(v, `${k} copied`, vv); r.append(b); } rows.append(r); });
      dcard.append(rows);
      const all = el('button', 'btn btn-wide', 'Copy all details'); all.onclick = () => copyText(BANK.map(([k, v]) => `${k}: ${v}`).join('\n'), 'Details copied', rows); dcard.append(all);
      dcard.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
    ct.append(em, cpm, addr, dn, dcard, el('p', 'muted', `Version ${C.version || ''}`)); main.append(ct);
    main.append(el('p', 'muted', 'Voices are AI-generated and play from files stored on your device. No speech is generated online.')); }  const sel = (vals, labels, cur, on) => { const s = el('select'); vals.forEach((v, i) => s.append(new Option(labels[i], v, false, v === cur))); s.onchange = () => on(s.value); return s; };
  const lab = (t, node) => { const l = el('label', '', t); l.append(node); return l; };
  render();
}
function greeting(p) { const h = new Date().getHours(); return (h < 12 ? 'Good morning, ' : h < 17 ? 'Good afternoon, ' : 'Good evening, ') + esc(p.name); }
