// Learner mode: Today, Session, Lesson, Review, Read, Test yourself, Progress, Settings.
import { db, uid } from './db.js';
import { C, play, W, shuffle, wordKey, sentKey, el, toast, bandFor } from './content.js';
import * as D from './drills.js';
import * as S from './session.js';
import { renderDashboard } from './dashboard.js';
import { renderPath, runLesson } from './path.js';

export async function renderLearner(root, ctx) {
  const { profile } = ctx; const st = { tab: 'today' };
  const marks = () => ctx.settings.marks !== false && (st.unitN ?? 0) <= 10;
  const styleName = () => ctx.settings.style || 'naskh';
  const dctx = { record: (drill, item, ok, ms) => S.recordAttempt(profile.id, st.unitN ?? 0, drill, item, ok, ms) };
  await S.ensureCards(profile.id, await S.currentUnit(profile.id));
  root.innerHTML = ''; const main = el('div'); root.append(main);
  const nav = el('div', 'bottom'); root.append(nav);
  const tabs = [['today', '🏠', 'Learn'], ['units', '📚', 'Units'], ['review', '🔁', 'Review'], ['read', '📖', 'Read'], ['progress', '📈', 'Progress'], ['more', '⚙️', 'More']];
  tabs.forEach(([k, ic, lab]) => { const b = el('button', k === st.tab ? 'active' : '', `<span>${ic}</span>${lab}`); b.onclick = () => { st.tab = k; render(); }; b.dataset.k = k; nav.append(b); });
  async function render() { [...nav.children].forEach(b => b.classList.toggle('active', b.dataset.k === st.tab)); main.innerHTML = ''; window.scrollTo(0, 0); await ({ today, units, review, read, progress, more, lesson, session, test, path }[st.tab])(); }
  const pctx = () => ({ profile, marks, styleName, dctx, unit0, aspirates, izafat, punctuation, unit11, sightDrill, go: t => { st.tab = t; render(); }, openLesson: (u, i) => { st.unitN = u.n; st.lessonU = u; st.lessonI = i; st.tab = 'path'; main.innerHTML = ''; runLesson(main, pctx(), u, i); } });
  async function path() { if (st.lessonU) { const u = st.lessonU, i = st.lessonI; st.lessonU = null; return runLesson(main, pctx(), u, i); } await header(greeting(profile), 'One small lesson at a time'); await renderPath(main, pctx()); }

  async function header(title, sub) { const h = el('div', 'row', ''); h.style.justifyContent = 'space-between'; h.innerHTML = `<div><h1>${title}</h1>${sub ? `<div class="muted">${sub}</div>` : ''}</div>`; const who = el('button', 'btn', `${profile.name} ▾`); who.onclick = ctx.switchProfile; h.append(who); main.append(h); }

  async function today() {
    const cur = await S.currentUnit(profile.id); const s = await S.stats(profile.id);
    await header(greeting(profile), `Unit ${cur} · ${C.units[cur].title} · one small lesson at a time`);
    await renderPath(main, pctx());
    if (s.wpm.length) { const last = s.wpm[s.wpm.length - 1]; main.append(el('div', 'card', `<b>Last reading speed:</b> ${last.wpm} words per minute <span class="pill ${bandFor(last.wpm)}">${bandFor(last.wpm)}</span>`)); }
    if (cur === 0 && !s.sessions) { const pl = el('div', 'card'); pl.innerHTML = '<h2>Already read some Urdu?</h2><p class="muted">A 2-minute placement check skips the units you already know.</p>'; const b = el('button', 'btn', 'Take the placement check'); b.onclick = () => placement(); pl.append(b); main.append(pl); }
    if (ctx.mode !== 'school') { const rp = el('button', 'btn btn-wide', 'Parent report for ' + profile.name); rp.onclick = () => parentReport(); main.append(rp); }
    if (cur === 0 && !s.sessions) main.append(el('div', 'card', `<h2>Five things before letter one</h2><ol style="padding-left:18px"><li><b>Right to left.</b> The first letter is on the right.</li><li><b>Letters join</b> like cursive and change shape. Ten never join forward: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span></li><li><b>Dots decide the letter.</b> <span class="ur">ب پ ت ٹ ث ن ی</span> share one body.</li><li><b>Small marks are vowels.</b> We keep them until unit 11.</li><li><b>Two typefaces</b>, Naskh for learning and Nastaliq for print. Switch in More.</li></ol>`));
  }

  // Session: review due cards, then the next lesson step of the current unit, then one read.
  async function session() {
    const cur = await S.currentUnit(profile.id); st.unitN = cur; const sess = await S.startSession(profile.id); const started = Date.now();
    await header('Session', 'Review → lesson → read · about 10 minutes'); const bar = el('div', 'progress', '<i style="width:0"></i>'); main.append(bar);
    const box = el('div'); main.append(box); let step = 0; const steps = [];
    const due = await S.dueCards(profile.id, 12); if (due.length) steps.push(() => reviewCards(due, box, () => next()));
    const u = C.units[cur]; const p = await S.getProgress(profile.id); const done = p.units[cur]?.steps || {};
    if (u.letters.length && !done.hear) steps.push(() => { box.innerHTML = ''; box.append(el('h2', '', 'New letters')); u.letters.map(c => C.by[c]).filter(Boolean).forEach(l => box.append(D.letterCard(l, dctx))); box.append(nextBtn(() => { done.hear = true; next(); })); });
    if (u.letters.length && !done.tell) steps.push(() => { box.innerHTML = ''; box.append(D.tellApart(u, dctx, (sc) => { done.tell = sc >= 7; box.append(nextBtn(next)); })); });
    if (u.words.length && !done.join) steps.push(() => { box.innerHTML = ''; box.append(D.joinIt(u, dctx, marks, () => { done.join = true; box.append(nextBtn(next)); })); });
    if (u.words.length) steps.push(() => { box.innerHTML = ''; box.append(D.readIt(u, dctx, marks)); box.append(nextBtn(next)); });
    if (u.letters.length && !done.write && profile.track !== 'adult') steps.push(() => { box.innerHTML = ''; box.append(D.writeIt(u, dctx, styleName, () => { done.write = true; })); box.append(nextBtn(next)); });
    if (u.words.length && !done.dict) steps.push(() => { box.innerHTML = ''; box.append(D.dictation(u, dctx, marks, (sc) => { done.dict = sc >= 4; box.append(nextBtn(next)); })); });
    if (u.words.length && !p.units[cur]?.passed) steps.push(() => { box.innerHTML = ''; box.append(D.quiz(u, dctx, marks, async (sc, t) => { const passed = await S.markUnit(profile.id, cur, sc, t); if (passed) { toast('Unit ' + cur + ' passed!'); await S.ensureCards(profile.id, cur + 1); } box.append(nextBtn(next)); })); });
    if (cur === 11) steps.push(() => { box.innerHTML = ''; box.append(unit11()); box.append(sightDrill()); box.append(nextBtn(next)); });
    if (u.sentences.length) steps.push(() => fluency(u, box, () => next()));
    if (cur === 0) steps.unshift(() => { box.innerHTML = ''; box.append(el('div', 'card', `<h2>Five things before letter one</h2><ol style="padding-left:18px"><li><b>Right to left.</b> The first letter is on the right.</li><li><b>Letters join</b> like cursive and change shape. Ten never join forward: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span></li><li><b>Dots decide the letter.</b> <span class="ur">ب پ ت ٹ ث ن ی</span> share one body.</li><li><b>Small marks are vowels.</b> We keep them until unit 11.</li><li><b>Two typefaces</b>, Naskh for learning and Nastaliq for print.</li></ol>`)); box.append(unit0()); box.append(nextBtn(next)); });
    if (cur === 0) steps.push(() => { box.innerHTML = ''; box.append(el('div', 'card', '<h2>Unit 0 done</h2><p>You know the five rules. Unit 1 starts with <span class="ur">ا ب ک ل م ن</span>.</p>')); S.markUnit(profile.id, 0, 10, 10).then(() => S.ensureCards(profile.id, 1)); box.append(nextBtn(next)); });
    async function next() { const pr = await S.getProgress(profile.id); pr.units[cur] = { ...(pr.units[cur] || {}), steps: done }; await db.put('progress', pr); step++; bar.firstChild.style.width = Math.min(100, step / Math.max(1, steps.length) * 100) + '%'; if (step >= steps.length) return finish(); steps[step](); }
    async function finish() { sess.bites = step; await S.endSession(sess); const mins = Math.round((Date.now() - started) / 60000); box.innerHTML = ''; box.append(el('div', 'card hero', `<div class="emoji">${profile.track === 'child' ? ['🌟', '🦁', '🎈', '🚀', '🌈'][Math.floor(Math.random() * 5)] : '✓'}</div><h2>Session done</h2><div class="muted">${step} bites in ${mins} min</div>`)); const b = el('button', 'btn btn-primary btn-wide', 'Back to Today'); b.onclick = () => { st.tab = 'today'; render(); }; box.append(b); }
    if (!steps.length) return finish(); steps[0]();
  }
  async function placement() { main.innerHTML = ''; await header('Placement check', 'Tap the letter you hear. We stop at the first unit that is not yet solid.'); const box = el('div'); main.append(box); let n = 1;
    const taughtPool = k => C.units.filter(u => u.n <= k).flatMap(u => u.letters).filter(c => C.by[c]);
    function stage() { const u = C.units[n]; if (!u || !u.letters.length) return finish(n - 1); box.innerHTML = ''; box.append(el('h2', '', `Unit ${n} letters`)); const pool = u.letters.filter(c => C.by[c]); const status = el('div', 'score'), choices = el('div', 'choices'); let round = 0, score = 0, target; box.append(status, choices);
      function next() { if (round >= 6) { return score >= 5 ? (n++, stage()) : finish(n - 1); } round++; target = pool[Math.floor(Math.random() * pool.length)]; status.textContent = `Round ${round}/6`; choices.innerHTML = ''; shuffle([target, ...shuffle(taughtPool(n).filter(c => c !== target)).slice(0, 5)]).forEach(c => { const t = el('button', 'tile ur', c); t.onclick = () => { if (c === target) { score++; t.classList.add('ok'); } else t.classList.add('no'); setTimeout(next, 400); }; choices.append(t); }); play('names/' + C.by[target].id); }
      next(); }
    async function finish(passedUpTo) { for (let k = 0; k <= passedUpTo; k++) await S.markUnit(profile.id, k, 10, 10); await S.ensureCards(profile.id, passedUpTo + 1); box.innerHTML = ''; box.append(el('div', 'card hero', `<h2>Start at unit ${passedUpTo + 1}</h2><div class="muted">${passedUpTo > 0 ? `Units 1–${passedUpTo} marked as known.` : 'Start from the beginning.'}</div>`)); const b = el('button', 'btn btn-primary btn-wide', 'Go'); b.onclick = () => { st.tab = 'today'; render(); }; box.append(b); }
    stage(); }
  async function parentReport() { const s = await S.stats(profile.id); const a = (await db.by('assessments', 'profileId', profile.id)).sort((x, y) => y.ts - x.ts)[0]; const cur = await S.currentUnit(profile.id); const lines = [`${profile.name} · Urdu Reader report · ${new Date().toLocaleDateString()}`, `Unit ${cur} of 12 (${s.unitsPassed} passed) · ${s.sessions} sessions`, `Letters solid: ${s.lettersMastered}/${s.letters} · Words solid: ${s.wordsMastered}/${s.words}`, s.wpm.length ? `Reading speed: ${s.wpm[s.wpm.length - 1].wpm} words/min (60 meets grade-2)` : 'Reading speed: not measured yet', a ? `Last assessment: ${new Date(a.ts).toLocaleDateString()}, ${a.orf?.cwpm ?? '-'} cwpm, ${a.band}` : '', `Next: 10 minutes a day, ${s.due} cards due. Ask ${profile.name} to read the unit ${cur} words aloud to you.`].filter(Boolean).join('\n');
    main.innerHTML = ''; await header('Parent report'); const c = el('div', 'card'); c.innerHTML = `<pre style="white-space:pre-wrap;font:inherit;margin:0">${lines}</pre>`; const sh = el('button', 'btn btn-primary', 'Share'); sh.onclick = async () => { try { if (navigator.share) await navigator.share({ text: lines }); else { await navigator.clipboard.writeText(lines); toast('Copied'); } } catch (e) {} }; const back = el('button', 'btn', 'Back'); back.onclick = () => { st.tab = 'today'; render(); }; c.append(el('div', 'row', ''), sh, back); main.append(c); }
  const nextBtn = fn => { const b = el('button', 'btn btn-primary btn-wide', 'Next'); b.onclick = fn; b.style.marginTop = '10px'; return b; };

  function reviewCards(cards, box, onDone) {
    let i = 0, right = 0; box.innerHTML = ''; const head = el('h2', '', `Review · ${cards.length} cards`), card = el('div', 'card center'), ctr = el('div', 'muted'); box.append(head, ctr, card);
    function show() { if (i >= cards.length) { toast(`${right}/${cards.length} remembered`); onDone(); return; } const c = cards[i]; ctr.textContent = `${i + 1} / ${cards.length}`; card.innerHTML = `<div class="ur big">${c.v || c.item}</div>`;
      const sub = el('div', 'muted', c.kind === 'letter' ? 'Say the letter name and sound' : 'Read the word aloud'); const row = el('div', 'row'); row.style.justifyContent = 'center'; const hear = el('button', 'btn', '🔊 Hear it'); hear.onclick = () => play(S.audioKeyFor(c));
      const reveal = el('div', 'muted', ''); const got = el('button', 'btn btn-primary', 'Got it'), miss = el('button', 'btn', 'Not yet');
      got.onclick = async () => { await S.gradeCard(c, true); right++; i++; show(); }; miss.onclick = async () => { await S.gradeCard(c, false); reveal.textContent = c.kind === 'letter' ? `${C.by[c.item].name} — ${C.by[c.item].hint}` : `${c.rom || ''} ${c.en ? '— ' + c.en : ''}`; play(S.audioKeyFor(c)); setTimeout(() => { i++; show(); }, 1400); };
      row.append(hear, miss, got); card.append(sub, row, reveal); }
    show();
  }

  function fluency(u, box, onDone, usePassage) {
    box.innerHTML = ''; const sents = usePassage ? [W(u.passage)] : u.sentences.map(W); const text = sents.map(s => marks() ? s.v : s.ur).join(' '); const words = text.split(' ').length;
    box.append(el('h2', '', 'Read for speed')); const p = el('div', 'card'); p.innerHTML = `<div class="ur" style="font-size:${usePassage ? 26 : 30}px;text-align:right">${text}</div>${usePassage ? `<div class="muted">${sents[0].en}</div>` : ''}<div class="muted">${words} words. Tap Start, read aloud, tap Stop. Read it twice.</div>`;
    const t = el('div', 'timer', '0.0 s'), start = el('button', 'btn btn-primary', 'Start'), stop = el('button', 'btn', 'Stop'), res = el('div', 'score'); let t0, h; stop.disabled = true;
    start.onclick = () => { t0 = Date.now(); start.disabled = true; stop.disabled = false; h = setInterval(() => t.textContent = ((Date.now() - t0) / 1000).toFixed(1) + ' s', 100); };
    stop.onclick = async () => { clearInterval(h); const sec = (Date.now() - t0) / 1000; const wpm = Math.round(words * 60 / sec); const prev = (await S.stats(profile.id)).wpm; const best = Math.max(0, ...prev.map(x => x.wpm)); res.textContent = `${wpm} words per minute${wpm > best ? ' · new personal best!' : best ? ` · best ${best}` : ''}`; await S.addWpm(profile.id, wpm, u.n); start.disabled = false; stop.disabled = true; start.textContent = 'Again'; };
    const row = el('div', 'row'); row.append(start, stop); if (!usePassage) sents.forEach((s, i) => row.append(D.playBtn(sentKey(u.n, i), true))); p.append(t, row, res); box.append(p, nextBtn(onDone));
  }

  async function units() { await header('Units', 'Tap a unit to open its lesson'); const p = await S.getProgress(profile.id); const cur = await S.currentUnit(profile.id);
    const libBtn = el('button', 'btn btn-wide', 'Letter library · all 38 letters'); libBtn.onclick = () => document.getElementById('library')?.scrollIntoView({ behavior: 'smooth' }); main.append(libBtn);
    const g = el('div', 'unitmap'); C.units.forEach(u => { const b = el('button', (p.units[u.n]?.passed ? 'done ' : '') + (u.n === cur ? 'cur ' : '') + (u.n > cur ? 'locked' : ''), `${u.n}`); b.title = u.title; b.onclick = () => { if (u.n > cur && !confirm(`Unit ${cur} is not passed yet. Open unit ${u.n} anyway?`)) return; st.unitN = u.n; st.tab = 'lesson'; render(); }; g.append(b); }); main.append(g); C.units.forEach(u => main.append(el('div', 'muted', `<b>${u.n}</b> ${u.title} — <span class="ur">${u.letters.join(' ')}</span> · ${u.hours ? `${u.hours[0]} h child / ${u.hours[1]} h adult` : ''}`)));
    const lh = el('h3', '', 'Letter library · dictionary order'); lh.id = 'library'; main.append(lh); const lib = el('div', 'choices'); lib.style.justifyContent = 'flex-start'; 'ا ب پ ت ٹ ث ج چ ح خ د ڈ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ہ ھ ئ ی ے'.split(' ').forEach(ch => { const l = C.by[ch]; if (!l) return; const t = el('button', 'tile small ur', ch); t.title = l.name; t.onclick = () => { play('names/' + l.id); const d = document.getElementById('libcard'); d.innerHTML = ''; d.append(D.letterCard(l, dctx)); d.scrollIntoView({ behavior: 'smooth', block: 'start' }); }; lib.append(t); }); main.append(lib); const lc = el('div', '', ''); lc.id = 'libcard'; main.append(lc); }

  async function lesson() { const u = C.units[st.unitN ?? 0]; await header(`Unit ${u.n} · ${u.title}`, u.focus); main.append(el('div', 'ur', u.title_ur));
    if (u.letters.length) { main.append(el('h3', '', '1 · Hear and see')); u.letters.map(c => C.by[c]).filter(Boolean).forEach(l => main.append(D.letterCard(l, dctx))); }
    if (u.n === 6) main.append(aspirates()); if (u.n === 0) { main.append(unit0()); main.append(punctuation()); } if (u.n === 10) { main.append(izafat()); main.append(punctuation()); } if (u.n === 11) { main.append(unit11()); main.append(sightDrill()); } if (u.n === 4) main.append(el('div', 'card', '<h2>Guess before you look</h2><p>Build <span class="ur">دور</span> <i>dūr</i> and <span class="ur">ہار</span> <i>hār</i> from tiles first. Which letters made the next letter start fresh? Then check the forms: <span class="ur">ا د ڈ ذ ر ڑ ز ژ و ے</span> never join forward. You discovered the rule instead of being told it.</p>'));
    if (u.letters.length) { main.append(el('h3', '', '3 · Tell it apart <span class="pill">recognition · self-check</span>')); main.append(D.tellApart(u, dctx)); }
    [[D.joinIt, '4 · Join it <span class="pill">production · self-check</span>'], [D.readIt, '5 · Read it <span class="pill">reading aloud · audio check</span>']].forEach(([f, t]) => { const x = f(u, dctx, marks); if (x) { main.append(el('h3', '', t)); main.append(x); } });
    if (u.letters.length) { main.append(el('h3', '', '6 · Write it <span class="pill">production · tracer check</span>')); main.append(D.writeIt(u, dctx, styleName)); }
    const d = D.dictation(u, dctx, marks); if (d) { main.append(el('h3', '', '7 · Dictation <span class="pill">production · self-check</span>')); main.append(d); }
    const q = D.quiz(u, dctx, marks, async (sc, t) => { const passed = await S.markUnit(profile.id, u.n, sc, t); if (passed) { toast('Unit ' + u.n + ' passed!'); await S.ensureCards(profile.id, u.n + 1); } }); if (q) { main.append(el('h3', '', '8 · Check <span class="pill">recognition · gate</span>')); main.append(q); }
    if (u.n === 12) main.append(selfTest());
  }
  function aspirates() { const c = el('div', 'card'); c.innerHTML = '<h2>Aspirates and the nasal vowel</h2><p class="muted">Write ھ after a consonant for a puff of breath (بھ پھ کھ گھ). ں nasalises the vowel before it.</p>'; const t = el('div', 'table'); t.innerHTML = `<table>${C.letters.aspirates.map(a => `<tr><td class="ur" style="font-size:26px">${a[0]}</td><td>${a[1]}</td><td class="ur" style="font-size:24px">${a[2]}</td><td>${a[3]} — ${a[4]}</td><td id="asp-${a[1].replace(/[^a-z]/g, '_')}"></td></tr>`).join('')}</table>`; c.append(t); C.letters.aspirates.forEach(a => c.querySelector('#asp-' + a[1].replace(/[^a-z]/g, '_'))?.append(D.playBtn('aspirates/' + [...a[1]].map(ch => /[a-z0-9]/i.test(ch) ? ch : '_').join(''), true))); return c; }
  function punctuation() { const c = el('div', 'card'); c.innerHTML = `<h2>Punctuation and numerals</h2><div class="table"><table>${C.letters.punctuation.map(x => `<tr><td class="ur" style="font-size:26px">${x[0]}</td><td>${x[2]}</td><td class="muted">${x[1]}</td></tr>`).join('')}</table></div><p class="muted">The full stop is a short line (۔), the comma is upside-down (،), the question mark is mirrored (؟). Numerals run left to right even inside Urdu text.</p><div class="grid-words">${C.letters.numerals.map(x => `<span>${x[0]}<small style="font-size:12px;color:var(--muted)"> ${x[1]}</small></span>`).join('')}</div>`; return c; }
  function izafat() { const z = C.letters.izafat; const c = el('div', 'card'); c.innerHTML = `<h2>Iẕāfat</h2><p>${z.explain}</p><div class="table"><table>${z.examples.map(e => `<tr><td class="ur" style="font-size:26px">${e[0]}</td><td>${e[1]}</td><td>${e[2]}</td></tr>`).join('')}</table></div>`; return c; }
  function unit0() { const c = el('div', 'card'); c.innerHTML = `<h2>Vowel marks</h2><p class="muted">Same three letters, three words: <span class="ur">گَل</span> gal (cheek) · <span class="ur">گِل</span> gil (clay) · <span class="ur">گُل</span> gul (flower).</p><div class="table"><table>${C.letters.diacritics.map(x => `<tr><td class="ur" style="font-size:26px">بـ${x.ch}</td><td>${x.name}</td><td>${x.sound}</td><td class="ur" style="font-size:22px">${x.example[0]}</td><td>${x.example[1]} — ${x.example[2]}</td><td id="d-${x.id}"></td></tr>`).join('')}</table></div><h3>Long vowels</h3><div class="table"><table>${C.letters.long_vowels.map(x => `<tr><td class="ur" style="font-size:24px">${x[0]}</td><td>${x[1]}</td><td class="ur" style="font-size:22px">${x[2].split(' ')[0]}</td><td>${x[2].split(' ').slice(1).join(' ')}</td></tr>`).join('')}</table></div><h3>Numerals</h3><div class="grid-words">${C.letters.numerals.map(x => `<span>${x[0]}<small style="font-size:12px;color:var(--muted)"> ${x[1]}</small></span>`).join('')}</div>`; C.letters.diacritics.forEach(x => c.querySelector('#d-' + x.id).append(D.playBtn('diacritics/' + x.id, true), D.playBtn('diacritics/' + x.id + '_ex', true))); return c; }
  function sightDrill() { const box = el('div', 'card'); box.innerHTML = '<h2>Tell the sight words apart</h2><p class="muted">Tap the word you hear · 10 rounds</p>'; const sw = C.letters.sight_words; const status = el('div', 'score'), choices = el('div', 'choices'), btn = el('button', 'btn btn-primary', 'Play word'); let round = 0, score = 0, target;
    function next() { if (round >= 10) { status.textContent = `Done: ${score}/10`; choices.innerHTML = ''; btn.textContent = 'Again'; btn.onclick = () => { round = 0; score = 0; next(); }; return; } round++; target = Math.floor(Math.random() * sw.length); status.textContent = `Round ${round}/10 · ${score} right`; choices.innerHTML = '';
      shuffle([target, ...shuffle(sw.map((w, i) => i).filter(i => i !== target)).slice(0, 5)]).forEach(i => { const t = el('button', 'tile small ur', sw[i]); t.onclick = () => { const ok = i === target; dctx.record('sight', sw[target], ok, 0); if (ok) { t.classList.add('ok'); score++; setTimeout(next, 450); } else { t.classList.add('no'); play('sight/' + String(i).padStart(2, '0')); } }; choices.append(t); });
      play('sight/' + String(target).padStart(2, '0')); btn.textContent = 'Play again'; btn.onclick = () => play('sight/' + String(target).padStart(2, '0')); }
    btn.onclick = next; box.append(status, btn, choices); return box; }
  function unit11() { const c = el('div', 'card'); c.innerHTML = '<h2>Sight words</h2><p class="muted">These twenty are a third of any Urdu text.</p>'; const g = el('div', 'words'); C.letters.sight_words.forEach((w, i) => { const d = el('div', 'word', `<div class="ur">${w}</div>`); d.append(D.playBtn('sight/' + String(i).padStart(2, '0'), true)); d.onclick = () => play('sight/' + String(i).padStart(2, '0')); g.append(d); }); c.append(g); c.insertAdjacentHTML('beforeend', `<h3>Naskh → Nastaliq</h3><div class="row">${['کتاب', 'پڑھنا', 'میں گھر میں ہوں'].map(w => `<div class="card" style="margin:0;text-align:center"><div class="ur" style="font-family:var(--naskh)">${w}</div><div class="ur nastaliq">${w}</div></div>`).join('')}</div><h3>Dictionary order</h3><div class="grid-words" style="font-size:26px">${'ا ب پ ت ٹ ث ج چ ح خ د ڈ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ہ ھ ء ی ے'.split(' ').map(x => `<span>${x}</span>`).join('')}</div><p class="muted">Turn vowel marks off in More and re-read earlier units.</p>`); return c; }

  async function review() { await header('Review', 'Cards due today'); const due = await S.dueCards(profile.id, 30); if (!due.length) { main.append(el('div', 'card center', '<div class="emoji">✓</div>Nothing due. Come back tomorrow, or open a unit.')); return; } const box = el('div'); main.append(box); reviewCards(due, box, () => { st.tab = 'today'; render(); }); }

  async function read() { await header('Read', 'Passages and sentences · read twice, watch your speed'); const cur = await S.currentUnit(profile.id);
    C.units.filter(u => u.passage && u.n <= Math.max(cur, 1)).reverse().forEach(u => { const box = el('div'); main.append(el('h3', '', `Passage · unit ${u.n}`)); main.append(box); fluency(u, box, () => {}, true); box.lastChild.remove(); });
    C.units.filter(u => u.sentences.length && u.n <= Math.max(cur, 1)).reverse().forEach(u => { const box = el('div'); main.append(el('h3', '', `Sentences · unit ${u.n}`)); main.append(box); fluency(u, box, () => {}); box.lastChild.remove(); }); }

  async function progress() { await header('Progress'); main.append(await renderDashboard(profile.id)); }

  function selfTest() { const c = el('div', 'card'); c.innerHTML = '<h2>Test yourself</h2><p class="muted">Five parts, like the teacher\'s assessment. This is your reading speed today, not a certificate.</p>'; const b = el('button', 'btn btn-primary', 'Start the reading test'); b.onclick = () => { st.tab = 'test'; render(); }; c.append(b); return c; }
  async function test() { await header('Test yourself', 'Five parts · a helper times you, or use the timer'); const A = C.letters.assessment; const results = {};
    const part = (title, items, key, secs) => { const c = el('div', 'card'); c.innerHTML = `<h2>${title}</h2><p class="muted">Tap Start, read aloud right to left, tap the ones you got wrong. Stop at ${secs} s.</p>`; const g = el('div', 'grid-words'); const wrong = new Set(); items.forEach((it, i) => { const s = el('span', 'item ur', it); s.onclick = () => { wrong.has(i) ? wrong.delete(i) : wrong.add(i); s.classList.toggle('wrong'); }; g.append(s); });
      const t = el('div', 'timer', String(secs)), start = el('button', 'btn btn-primary', 'Start'), res = el('div', 'score'); let t0, h; start.onclick = () => { t0 = Date.now(); start.disabled = true; h = setInterval(() => { const left = secs - (Date.now() - t0) / 1000; t.textContent = Math.max(0, left).toFixed(0); if (left <= 0) { clearInterval(h); const n = Math.min(items.length, parseInt(prompt('How many did you reach?', String(items.length))) || 0); const score = n - [...wrong].filter(i => i < n).length; results[key] = score; res.textContent = `${score} correct per minute`; S.recordAttempt(profile.id, 12, 'self-' + key, key, true, score); start.disabled = false; } }, 250); }; c.append(t, start, g, res); return c; };
    main.append(part('1 · Letter sounds', shuffle(C.letters.letters.concat(C.letters.letters)).slice(0, 60).map(l => l.ch), 'letters', 60));
    main.append(part('2 · Nonwords', shuffle(A.nonwords.concat(A.nonwords)).slice(0, 30), 'nonwords', 60));
    main.append(part('3 · Familiar words', shuffle(C.units.flatMap(u => u.words.map(w => w[0]))).slice(0, 40), 'words', 60));
    const pc = el('div', 'card'); pc.innerHTML = `<h2>4 · Passage</h2><div class="ur" style="font-size:26px;text-align:right">${A.passage}</div>`; const words = A.passage.split(' ').length; const t = el('div', 'timer', '0.0 s'), start = el('button', 'btn btn-primary', 'Start'), stop = el('button', 'btn', 'Stop'), errs = el('input'), res = el('div', 'score'); errs.type = 'number'; errs.min = 0; errs.value = 0; errs.style.width = '80px'; let t0, h; stop.disabled = true;
    start.onclick = () => { t0 = Date.now(); start.disabled = true; stop.disabled = false; h = setInterval(() => t.textContent = ((Date.now() - t0) / 1000).toFixed(1) + ' s', 100); };
    stop.onclick = async () => { clearInterval(h); const sec = (Date.now() - t0) / 1000; const cwpm = Math.round(Math.max(0, words - (+errs.value || 0)) * 60 / sec); results.cwpm = cwpm; const lvl = cwpm > 90 ? 'exceeds the grade-2 standard' : cwpm >= 60 ? 'meets the standard' : cwpm > 0 ? 'below the standard: repeat the units the earlier parts flagged' : 'nonreader: restart at unit 1'; res.textContent = `${cwpm} cwpm — ${lvl}`; await S.addWpm(profile.id, cwpm, 12); await db.put('assessments', { id: uid(), profileId: profile.id, ts: Date.now(), letters: results.letters, nonwords: results.nonwords, words: results.words, orf: { cwpm, seconds: Math.round(sec), errors: +errs.value || 0 }, band: bandFor(cwpm), by: 'self' }); start.disabled = false; stop.disabled = true; };
    const row = el('div', 'row'); row.append(start, stop, el('span', 'muted', 'errors:'), errs); pc.append(t, row, res); main.append(pc);
    const qc = el('div', 'card'); qc.innerHTML = `<h2>5 · Comprehension</h2><ol style="padding-left:18px">${A.questions.map(q => `<li class="ur" style="font-size:22px;text-align:right">${q}</li>`).join('')}</ol><details><summary>Answer key</summary><ol style="padding-left:18px">${A.answers.map(a => `<li>${a}</li>`).join('')}</ol></details><div class="table" style="margin-top:8px"><table><tr><th>cwpm</th><th>Level</th></tr><tr><td>&gt; 90</td><td>exceeds grade-2 standard</td></tr><tr><td>60–90</td><td>meets standard</td></tr><tr><td>1–59</td><td>below standard</td></tr><tr><td>0</td><td>nonreader</td></tr></table></div>`; main.append(qc); }

  async function more() { await header('More'); const c = el('div', 'card'); c.innerHTML = '<h2>Settings</h2>';
    const track = sel(['child', 'adult', 'heritage'], ['Child (5–10)', 'Adult, new to Urdu', 'Speaks Urdu, can\'t read'], profile.track, async v => { profile.track = v; await db.put('profiles', profile); ctx.apply(); });
    const style = sel(['naskh', 'nastaliq'], ['Naskh (learning)', 'Nastaliq (print)'], ctx.settings.style || 'naskh', v => ctx.set('style', v));
    const marksCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.marks !== false ? 'checked' : ''}> Show vowel marks (until unit 10)`); marksCb.querySelector('input').onchange = e => ctx.set('marks', e.target.checked);
    const size = sel(['1', '1.25', '1.5'], ['Normal text', 'Large', 'Extra large'], String(ctx.settings.scale || '1'), v => ctx.set('scale', v));
    const romCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.rom === false ? '' : 'checked'}> Show romanisation (Latin letters)`); romCb.querySelector('input').onchange = e => ctx.set('rom', e.target.checked);
    const aoCb = el('label', 'row', `<input type="checkbox" ${ctx.settings.audioOnly ? 'checked' : ''}> Audio-first mode (words hidden until tapped)`); aoCb.querySelector('input').onchange = e => ctx.set('audioOnly', e.target.checked);
    const sp = sel(['0', '0.05', '0.12'], ['Normal letter spacing', 'Wider', 'Widest (dyslexia-friendly)'], String(ctx.settings.spacing || '0'), v => ctx.set('spacing', v));
    c.append(lab('Track', track), lab('Script', style), lab('Text size', size), lab('Letter spacing', sp), marksCb, romCb, aoCb); main.append(c);
    const d = el('div', 'card'); d.innerHTML = '<h2>Data</h2><p class="muted">Everything stays on this phone. Export to keep a backup or move to another phone.</p>'; const ex = el('button', 'btn', 'Export backup (JSON)'); ex.onclick = () => ctx.exportBackup(); const im = el('input'); im.type = 'file'; im.accept = '.json'; im.onchange = async e => { const f = e.target.files[0]; if (!f) return; const n = await db.importAll(JSON.parse(await f.text())); toast(`Imported ${n} records`); }; const reset = el('button', 'btn btn-danger', 'Reset this profile\'s progress'); reset.onclick = async () => { if (!confirm('Delete all progress for ' + profile.name + '?')) return; for (const s of ['cards', 'attempts', 'sessions', 'assessments']) for (const r of await db.by(s, 'profileId', profile.id)) await db.del(s, r.id); await db.del('progress', profile.id); toast('Reset'); st.tab = 'today'; render(); }; d.append(el('div', 'row', ''), ex, lab('Import backup', im), reset); main.append(d);
    const sw = el('button', 'btn btn-wide', 'Switch profile / mode'); sw.onclick = ctx.switchProfile; main.append(sw);
    main.append(el('p', 'muted', 'Urdu Reader · course and evidence at github.com/oyekamal/urdu-reading-course · audio is machine voice (non-commercial licence)')); }
  const sel = (vals, labels, cur, on) => { const s = el('select'); vals.forEach((v, i) => s.append(new Option(labels[i], v, false, v === cur))); s.onchange = () => on(s.value); return s; };
  const lab = (t, node) => { const l = el('label', '', t); l.append(node); return l; };
  render();
}
function greeting(p) { const h = new Date().getHours(); return (h < 12 ? 'Good morning, ' : h < 17 ? 'Good afternoon, ' : 'Good evening, ') + p.name; }
